config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :projets, only: [ :index, :show ]

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/projet.rb
class Projet < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
    @projets = Projet.all
  end
end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  def index
    @projets = Projet.all
  end

  def show
    @projet = Projet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="content-wrapper">
      <%= yield %>
    </div>
    <%#= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="home-content row align-items-center d-flex justify-content-center">
  <div class="home-background">
    <div class="line-container">
      <div class="lines line1"></div>
      <div class="lines line2"></div>
      <div class="lines line3"></div>
      <div class="lines line4"></div>
      <div class="lines line5"></div>
    </div>
  </div>

  <div class="blob">
    <svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 310 350">
    <path d="M156.4,339.5c31.8-2.5,59.4-26.8,80.2-48.5c28.3-29.5,40.5-47,56.1-85.1c14-34.3,20.7-75.6,2.3-111  c-18.1-34.8-55.7-58-90.4-72.3c-11.7-4.8-24.1-8.8-36.8-11.5l-0.9-0.9l-0.6,0.6c-27.7-5.8-56.6-6-82.4,3c-38.8,13.6-64,48.8-66.8,90.3c-3,43.9,17.8,88.3,33.7,128.8c5.3,13.5,10.4,27.1,14.9,40.9C77.5,309.9,111,343,156.4,339.5z"/>
    </svg>
  </div>

  <div class="about">
    <h1>About <b>me .</b></h1>
  </div>

  <div class="vertical-name">
    <h7>ESTELLE SAGET</h7>
  </div>
</div>

<div class="portrait">
  <div class="image-portrait">
    <%= image_tag ('profile_picture.png'), class: 'portrait-picture'  %>
  </div>

  <div class="portrait-description">
    <div class="portrait-title">
      <h1>I'm Estelle</h1>
      <br>
      <br>
      <p>Product Manager and Web Developer with an IT sales background. I'm passionate about product & UI/UX Design, mobile & web projects as well as branding, and animations. With my experience at Le Wagon, I know how to develop a web site by using design thinking.
      </p>
      <br>
      <p>With a background in Front-End Development, I understand the constraints of the web and am able to design and build around them effectively. My goal is to help people build better and more meaningful products.
      </p>
    </div>
  </div>
</div>

<div class="cv">
  <h1>My experience</h1>
  <div class="cards">
    <div class="card-category">
      <div class="title">Account Manager @ Numendo</div>
      <div class="date">Oct 2018 - Nov 2019</div>
      <div class="missions">
        Accompagnement des clients grands comptes sur le développement de projets digitaux.
        Chasseuse de têtes sur les profils de Développeurs, Designers & Chefs de projets techniques
      </div>
    </div>

    <div class="card-category">
      <div class="title">Account Manager @ Ippon</div>
      <div class="date">Sept 2017 - Oct 2018</div>
      <div class="missions">
        Accompagnement des clients du secteur Industrie sur le développement de projets digitaux.
        Chasseuse de têtes sur les profils de Développeurs Fullstack.
      </div>
    </div>

    <div class="card-category">
      <div class="title">Account Manager @ IBM</div>
      <div class="date">Sept 2016 - Oct 2017</div>
      <div class="missions">
        En binôme avec le Directeur Commercial de la BU Mid-Market France, j'ai en charge de développer un portefeuille de plus de 100 comptes et de les accompagner dans leur transformation digitale.
      </div>
    </div>

    <div class="card-category">
      <div class="title">Business Developer @ Ippon</div>
      <div class="date">Juil 2015 - Avr 2016</div>
      <div class="missions">
        Responsable d'un nouvel espace de Coworking à Paris 16, j'ai pour rôle de détecter et recruter plus de 20 Startups du Digital et les accompagner dans leur développement.
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<h1>My first view contact 🚀</h1>

app/views/pages/home.html.erb
<div class="home-content row align-items-center d-flex justify-content-center">
  <div class="home-background">
    <div class="line-container">
      <div class="lines line1"></div>
      <div class="lines line2"></div>
      <div class="lines line3"></div>
      <div class="lines line4"></div>
      <div class="lines line5"></div>
    </div>
  </div>

<div class="banner">
  <div class="image-banner">
      <%= image_tag ('es-banner.jpg'), class: 'profile-picture'  %>
      <div class="title-banner">
        <h1>Hello.</h1>
      </div>
    </div>

    <div class="description-banner text-center">
      <p>Personal Website</p>
      <p> <span>Creativity</span> & <span>Technology</span></p>
    </div>

    <div class="vertical-name">
      <h7>ESTELLE SAGET</h7>
    </div>
  </div>
  <div class="arrow"></div>
</div>

<div class="projets">
  <h1>My projects</h1>
</div>

<section id="portfolio">
  <% @projets.each do |projet| %>
    <div class="project">
      <img class="project__image" src="https://images.unsplash.com/photo-1472437774355-71ab6752b434?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=dd4d735954f33290fbf984e4eb7abe32&auto=format&fit=crop&w=700&q=80" />
      <p><%= projet.name %></p>
      <h3 class="grid__title"><%= projet.technologies %></h3>
      <div class="grid__overlay">
        <button class="viewbutton"><%= link_to 'view more', projet_path(projet)%></button>
      </div>
    </div>
    <!-- <div class="project">
      <img class="project__image" src="https://images.pexels.com/photos/983831/pexels-photo-983831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" />
      <p>websites</p>
      <h3 class="grid__title"> front-end</h3>
      <div class="grid__overlay">
        <button class="viewbutton">view more</button>
      </div>
    </div>

    <div class="project">
      <img class="project__image" src="https://images.pexels.com/photos/316891/pexels-photo-316891.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" />
      <p>pure css</p>
      <h3 class="grid__title"> front-end</h3>
      <div class="grid__overlay">
        <button class="viewbutton">view more</button>
      </div>
    </div>

    <div class="project">
      <img class="project__image" src="https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" />
      <p>web apps</p>
      <h3 class="grid__title"> full-stack</h3>
      <div class="grid__overlay">
        <button class="viewbutton">view more</button>
      </div>
    </div>

    <div class="project">
      <img class="project__image" src="https://images.unsplash.com/photo-1472437774355-71ab6752b434?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=dd4d735954f33290fbf984e4eb7abe32&auto=format&fit=crop&w=700&q=80" />
      <p>daily ui</p>
      <h3 class="grid__title"> ui/ux design</h3>
      <div class="grid__overlay">
        <button class="viewbutton">view more</button>
      </div>
    </div>
    <div class="project">
      <img class="project__image" src="https://images.unsplash.com/photo-1483058712412-4245e9b90334?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7c5008952226f48ed4bf5d3ea64ff545&auto=format&fit=crop&w=700&q=80" />
      <p>websites</p>
      <h3 class="grid__title"> front-end</h3>
      <div class="grid__overlay">
        <button class="viewbutton">view more</button>
      </div>
    </div>

    <div class="project">
      <img class="project__image" src="https://images.unsplash.com/photo-1509395176047-4a66953fd231?ixlib=rb-0.3.5&s=a4b3dc4bee43da458f6aa5c05be6bfc4&auto=format&fit=crop&w=700&q=80" />
      <p>pure css</p>
      <h3 class="grid__title"> front-end</h3>
      <div class="grid__overlay">
        <button class="viewbutton">view more</button>
      </div>
    </div>

    <div class="project">
      <img class="project__image" src="https://images.unsplash.com/photo-1481762554390-ff5562748bdf?ixlib=rb-0.3.5&s=1b7f850b7f8f702e237b0f81c0ec0bf5&auto=format&fit=crop&w=700&q=80" />
      <p>web apps</p>
      <h3 class="grid__title"> full-stack</h3>
      <div class="grid__overlay">
        <button class="viewbutton">view more</button>
      </div>
    </div>

    <div class="project">
      <img class="project__image" src="https://images.unsplash.com/photo-1463620695885-8a91d87c53d0?ixlib=rb-0.3.5&s=e5bf2f64858b8abe2a386b0c6df594e4&auto=format&fit=crop&w=700&q=80" />
      <p>daily ui</p>
      <h3 class="grid__title"> ui/ux design</h3>
      <div class="grid__overlay">
        <button class="viewbutton">view more</button>
      </div>
    </div> -->
    <div class="overlay">
      <div class="overlay__inner">
        <button class="close">close X</button>
        <img>
      </div>
    </div>
  <% end  %>
</section>

app/views/projets/index.html.erb
<div class="container mx-auto">
      <% @projets.each do |projet| %>
        <p> <%= projet.name %></p>
        <% end  %>
</div>

app/views/projets/show.html.erb
<div class="home-content row align-items-center d-flex justify-content-center">
  <div class="home-background">
    <div class="line-container">
      <div class="lines line1"></div>
      <div class="lines line2"></div>
      <div class="lines line3"></div>
      <div class="lines line4"></div>
      <div class="lines line5"></div>
    </div>
  </div>

  <div class="show-name">
    <h1><%= @projet.name %></h1>
  </div>

  <div class="vertical-name">
    <h7>ESTELLE SAGET</h7>
  </div>

  <div class="arrow"></div>
</div>





<div class="projet-container">
  <div class="projet">
    <h2>Projet</h2>
  </div>

  <div class="projet-name">
    <h1><%= @projet.name %></h1>
  </div>

  <div class="projet-button">

  </div>

  <div class="mockup">
    <%= image_tag ('guesswhat-3.jpg'), class: 'guesswhat-mockup' %>
  </div>

</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <input type='checkbox' id='toggle' style='display:none;' />
  <label class='toggle-btn toggle-btn__cross' for='toggle'>
    <div class="bar"></div>
    <div class="bar"></div>
    <div class="bar"></div>
  </label>
  <nav>
    <ul>
      <li><a><%= link_to 'Home', home_path %></a></li>
      <li><a><%= link_to 'About', about_path %></a></li>
      <li><a><%= link_to 'Contact me', contact_path %></a></li>
    </ul>
  </nav>
</div>